### ISSUE TITLE
Modelagem do banco

### ISSUE THREAD

**Issue by RicCoutinho** [teste-de-progresso/progress-test-backend#53]
**Atual:**
![image](https://user-images.githubusercontent.com/44474987/95131918-49ef1b00-0735-11eb-9dbc-033dfe2d6980.png)

**Ideia 1:**
![image](https://user-images.githubusercontent.com/44474987/95131722-f2e94600-0734-11eb-8bcd-bdc1ca5c66c2.png)

**Ideia 2:**
![image](https://user-images.githubusercontent.com/44474987/95145540-e4f5ee00-0751-11eb-9c43-37206cff5fce.png)

Será que essa modelagem se aplicará a todos os cursos?

**Comment by lcrmj** [comment]
materia: category_id, sub_category_id
sub_category: category_id
category: axis_id
axis: n/a

**Comment by geonizeli** [comment]
por que matéria deveria ter `sub_category_id` e `category_id` e não uma relação polifórmica?

**Comment by geonizeli** [comment]
solucionado no PR #65
