### ISSUE TITLE
Observações Eugênio

### ISSUE THREAD

**Issue by RicCoutinho** [teste-de-progresso/progress-test-backend#54]
---------------------------
OBSERVAÇÕES SOBRE O SISTEMA
---------------------------

Tela de Entrada:
  
- [x]  01 - Incluir o rótulo "Filtros" antes das caixas de opções.
  
- [x]  02 - As caixas de opções devem seguir a seguinte sequência:
       "Grau de Dificuldade" - "Habilidade (Taxonomia de Bloom)" - "Tipo de Questão" - "Tema" - "Eixo Curricular" - "Categoria (Teste de Progresso)" - "Status";
	   OBS.: talvez a disposição desses itens na horizontal pode não ser a mais adequada, nesse caso, vale tentar uma disposição na vertical à esquerda. 
  
- [x]  03 - Incluir os rótulos correspondentes acima de cada caixa de opções listada no item 2.
  
- [x]  04 - Para cada filtro deve ser possível selecionar mais de uma opção.
  
- [x]  05 - Na caixa de opções "Grau de Dificuldade" a opção "Medium" deve ser substituída por "Médio".
  
- [x]  06 - A sequência correta de opções para a caixa de opções "Habilidade (Taxonomia de Bloom)" é:
      - recordar;
	  - compreender;
	  - aplicar;
	  - analisar;
	  - avaliar;
	  - criar.
  
- [x]  07 - A sequência correta de opções para a caixa de opções "Tipo de Questão" é:
      - resposta única;
	  - afirmação incompleta;
	  - resposta múltipla;
	  - foco negativo;
	  - asserção e razão;
	  - lacuna;
	  - interpretação;
	  - associação;
	  - ordenação ou seriação;
      - alternativas constantes.
	  	  
- [x]  08 - Quando alguma opção de "Tema" for selecionada, as caixas "Eixo Curricular" e "Categoria (Teste de Progresso)" devem ser automaticamente preenchidas e dasabilitadas.
  
- [x]  09 - ~Quando alguma opção de "Eixo Curricular" for selecionada, as caixas "Tema" e "Categoria (Teste de Progresso)" devem exibir apenas as opções condizentes com o eixo selecionado.~ a seleção de temas é feita por um Search Select, implementar essa ideia é custoso por enquanto~
  
- [x]  10 - Quando alguma opção de "Categoria (Teste de Progresso)" for selecionada, as caixas "Tema" e "Eixo Curricular" devem exibir apenas as opções condizentes com o eixo selecionado.

- [x]  11 - Ao clicar no ícone X, todas as caixas de opções devem voltar para a opção "em branco".
  
- [x]  12 - ~Incluir o rótulo "Exibição" antes das caixas de opções que permite selecionar o número de itens para visualização.~ até 15 resultados fica melhor
  
- [x]  13 - A caixa que exibe as opções de número de itens para visualização deve seguir o mesmo padrão das outras, ou seja, deve aparecer a "setinha para baixo" à direita.
  
- [x]  14 - ~Falta um botão que leve o usuário à tela de cadastro~ provavelmente o usuário só estava sem a permissão pra isso
  
 
Tela de Cadastro:

- [x]  01 - ~A edição das "alterntivas incorretas" está desabilitada. ~ foi alguma questão que foi gerada pelo seed e alternatives estava null, ai da esse problema, não acontece em um cadastro regular, é bom checar 
  
- [x]  02 - "Alternativas incorretas" deve ser renomeado para "Distratores".
  
- [x]  03 - O cadastro dos distratores deve estar em uma tela separada da tela de cadastro da alternativa correta.
  
- [x]  04 - A tela de cadastro das características deve seguir o layout apresentado na figura tela_cadstro_caracteristicas.jpg em anexo.
  
- [x]  05- Quando a opção "Própria" for selecionada, a caixa "Fonte" deve ser preenchida automaticamente com "UNIFESO" e o "Ano" preenchido com o ano corrente e ambas as caixas devem ser desabilitadas.
  
- [x]  06 - Quando a opção "Terceiro" for selecionada, as caixas "Fonte" e "Ano" devem estar livres para edição.
  
- [x]  07 - Quando a opção "Tema" for selecionada, os rótulos "Eixo curricular" e "Categoria (Teste de Progresso)" devem ser preenchidos automaticamenete.
  
- [x]  08 - O cadastro do revisor e de seu parecer deve estar em uma tela separada da tela de cadastro de características.
  
- [x]  09 - A tela de cadastro do revisor deve seguir o layout apresentado na figura tela_cadastro_revisor.jpg em anexo.
    
- [x]  10 - O botão "Registrar" deve ser habilitado apenas quando o "Status" for "Aprovada".
  
- [x]  11 - É importante avisar ao autor que uma vez registrada a questão não pode mais ser alterada.
  
- [x]  12 - Sempre que o botão "Finalizar" for pressionado pelo autor/revisor deve aparecer uma caixa de mensagem avisando que uma notificação será enviada ao revisor/autor.
  
- [x]  13 - O botão "Finalizar" deve ser habilitado apenas quando todos os campos do cadastro da questão estiverem preenchidos, lembrando que os campos "Instrução" e "Suporte" não são obrigatórios.
Temos que procurar saber como implementar isso de forma limpa.
  
- [x]  14 - Para o revisor os únicos campos que devem estar habilitados são "Status" e "Observações" e os botões "Retornar", "Progredir" e "Finalizar".

**Comment by geonizeli** [comment]
Vou abrir issues separadas apara o as observações 13 e 14.
